### ISSUE TITLE
Optionally always generate same color pallete

### ISSUE THREAD

**Issue by Erol444** [alan-turing-institute/distinctipy#23]
## Start with `why`

I believe this would be useful in AI field - where you have X number of classes as an output of an eg. object detection. In that case, it's much better to have bounding boxes with the same color each time you run the program - people get used to that color, so they don't need to look at the label of some object (to determine whether detector's output is correct).

## Move to `what`:

Add an option to always get the same palette for the same number of colors.

## End with `how`:

So it would be something similar to what [seaborn](https://github.com/mwaskom/seaborn) does;
```
import seaborn
p = seaborn.color_palette("husl", 9)
# p will always be the same
```
Issue with seaborn is that it's huge and has tons of dependencies, which isn't ideal if you just want to get color palettes.
If you are using random numbers to generate colors, maybe we could insert seed num for these, so the output color palette would always look the same.

Thoughts?

**Comment by jack89roberts** [comment]
Hi @Erol444 , thanks for using distinctipy! There are two ways to get the same colours on repeated runs:

- You can specify a value for the `rng` parameter of `distinctipy.get_colors` (see [docs here](https://distinctipy.readthedocs.io/en/latest/api.html#module-distinctipy.distinctipy), introduced in version 1.2.0).
- You could use the built-in list of 200 colours (see [docs here](https://distinctipy.readthedocs.io/en/latest/api.html#distinctipy.colorsets.get_colors)). You can also use (distinctipy.colorsets.set_palette)[https://distinctipy.readthedocs.io/en/latest/api.html#distinctipy.colorsets.set_palette] to set matplotlib to use these 200 colours.

Do these fit what you need?

**Comment by Erol444** [comment]
Thanks @jack89roberts , thanks exactly what I needed! Sometimes I should follow the RTFM rule 😅
Thanks again, Erik
