### ISSUE TITLE
Python 3.7 is broken in 1.3.x

### ISSUE THREAD

**Issue by Erotemic** [alan-turing-institute/distinctipy#36]
The package metadata indicates the Python 3.7 is supported, however, as of version 1.3.2 the `distinctipy/__init__.py` now uses [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html), which is only available in Python 3.8+.

There are two solutions:

1. Revert to using `__init__.py` as the single source of version truth (which is probably difficult if you want to stick with pyproject.toml structure)
2. Change `requires-python = ">=3.7"` to `requires-python = ">=3.8"` in pyproject.toml

The second option is probably the best. It might also be worthwhile to yank 1.3.2 and 1.3.3 because Python 3.7 might incorrectly think that those packages are comaptible with it.

**Comment by jack89roberts** [comment]
Thanks for flagging this @Erotemic - I'll work on option 2 now since Python 3.7 is end of life.
